#                                                                        #
# Settings Configuration for the Pixur Aws package                       #
#                                                                        #
# Production Context                                                     #
#                                                                        #

Jayvee:
  Aws:
    #key: <access_key>
    #secret: <secret_key>
    #region: <preferred_region>