#                                                                        #
# Settings Configuration for the Pixur Aws package                       #
#                                                                        #
# Production Context                                                     #
#                                                                        #

Jayvee:
  Aws:
    sdk:
      #credentials:
      #  key: <access_key>
      #  secret: <secret_key>
      #region: <preferred_region>